### PR TITLE
Fixes Sha256bitPadded embed library 

### PR DESCRIPTION
**Pull request by petscheit**
As of ZoKrates 0.6.0 bools now have their own type. Quick fix and a test

### CODE REVIEW

**Comment by Schaeff** [comment]
LGTM! @dark64 can you have a look? Are we still missing something with the new embeds?

**Comment by dark64** [comment]
> LGTM! @dark64 can you have a look? Are we still missing something with the new embeds?

Looks good to me as well. Unrelated to this, noticed `256bitPadded` test is missing for the native sha as well.

**Comment by petscheit** [comment]
True, those tests are missing. I will add one tomorrow

**Review by dark64 — APPROVED** [review]

**Review by Schaeff — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
