### PR TITLE
Graceful handling of unconstrained variable detection

### PR DESCRIPTION
**Pull request by dark64**

### CODE REVIEW

**Comment by dark64** [comment]
Should we include this in the changelog? @Schaeff

**Comment by Schaeff** [comment]
Yes, this is user facing.

**Review by Schaeff — CHANGES_REQUESTED** [review]
This would benefit from tests in this module.

**Comment by Schaeff** [comment]
I missed the tests were actually there, my bad! Let's just make them stricter by not using `is_err` and `is_ok`

**Review by Schaeff — APPROVED** [review]

**Pull request merged**
