### PR TITLE
Marlin solidity verifier

### PR DESCRIPTION
**Pull request by nirvantyagi**
**Work in progress**
This PR implements the verifier for Marlin proofs produced in ZoKrates. It does the following:

- Updates Marlin data structures from raw bytes to structured group and field elements
- Updates `arkworks` dependencies to version `0.3`
- Adds `zokrates_solidity_test` crate to provide utils for executing and testing solidity contracts on a local EVM
- Implements `SolidityCompatibleScheme` for Marlin by providing verifier contract

This PR supersedes #1035 and #1036.

### CODE REVIEW

**Comment by nirvantyagi** [comment]
Creating this draft PR to document some changes to `ark_marlin` that we can hopefully get included in the next version release.

https://github.com/arkworks-rs/marlin/pull/83: Provides a constructor for the `IndexInfo` struct merged by @Schaeff

**Comment by nirvantyagi** [comment]
Marlin uses Fiat-Shamir hash challenges to create a non-interactive proof. Currently the `ark_marlin` implementation uses a hard-coded `ChaChaRng`-derived approach to generating hash challenges. That isn't ideal for solidity as chacha is not supported with low gas costs (as far as I'm aware). PR (https://github.com/arkworks-rs/marlin/pull/86) abstracts the Fiat-Shamir functionality in `ark_marlin` to allow for use of other hash functions, e.g., keccak256.

**Comment by nirvantyagi** [comment]
I am marking the PR ready for review. A couple notes:

- It is still dependent on a fork of `ark-marlin`. If https://github.com/arkworks-rs/marlin/pull/86 is merged, then the dependency can be updated to the cherry-picked commit of `v0.3.0`. Once `ark-marlin` moves to `v0.4.0` I believe there will be some larger backwards compatibility issues that need to be dealt with.
- I included a small EVM testing library `zokrates_solidity_test` that I used for unit testing. If that library isn't desired, it can be removed along with the unit test. I didn't implement any integration tests for the contract.

**Review by Schaeff — APPROVED** [review]
LGTM 🚀

**Pull request merged**
