### PR TITLE
WIP: Adding compile and verify script/minor readme update

### PR DESCRIPTION
**Pull request by edisinovcic**
Adding just a script for getting started even easier, the place of the script can be changed. 

In which branch should I merge this one?

### CODE REVIEW

**Comment by Schaeff** [comment]
Hi @edisinovcic thanks the suggestion!
If I understand correctly, this is specific to IntelliJ?
It's clear we could do a better job with the `examples` folder but I'm not sure a script that encapsulates the whole pipeline is what we need. Maybe you can share what you had trouble with and we can figure out what to improve?

**Comment by edisinovcic** [comment]
No, it's vscode specific, it's just for debugging scripts, so it's not intended to be used inside images. It can be used for debugging bash scripts for example compile and validate that I've created for the whole workflow. 

Example folder is there but definitely, some other place should be better to store the script and files, for example inside zokrates_cli/examples. What do you think?

**Comment by edisinovcic** [comment]
Also there is a bug with latest version of rustc and that's why integration tests are failing.

**Comment by Schaeff** [comment]
> Also there is a bug with latest version of rustc and that's why integration tests are failing. The solution is to lower the version of the compiler used or to update the code. Problem is that there are only two version on dockerhub which was updated 19 hours ago.
> 
> https://hub.docker.com/r/rustlang/rust/tags

This was fixed on develop, can you make your change target that?

> No, it's vscode specific, it's just for debugging scripts, so it's not intended to be used inside images. It can be used for debugging bash scripts for example compile and validate that I've created for the whole workflow.

I'm skeptical about adding something specific to an IDE and I'm struggling to understand what problem this is solving.
In general I think that any changes that improve onboarding for users should be done in `zokrates_book` by default.

**Comment by edisinovcic** [comment]
> This was fixed on develop, can you make your change target that?
Will do.
> I'm skeptical about adding something specific to an IDE and I'm struggling to understand what problem this is solving.
> In general I think that any changes that improve onboarding for users should be done in `zokrates_book` by default.
Okay, the idea was having script that does all the stuff and you send all the arguments in one line. Currently it's pretty good so it's maybe overengineered (no need for it).

**Comment by Schaeff** [comment]
I see, but why would you want to do everything in one go? ie usually you compile once, do a setup once, and run and prove many times. We have an open issue to combine run and prove here #261 but not agreed yet.

**Comment by edisinovcic** [comment]
True that. Then I will close this one.

**Pull request closed without merging**
